### ISSUE TITLE
afficher les infos concernant la personne  qui s'est connectée

### ISSUE THREAD

**Issue by marwaKotti** [Jasig/phpCAS#183]
je veux afficher les infos concernant la personne qui s'est connectée  ( son mail , son uid , son prénom) 
alors comment faire  SVP ?

**Comment by jfritschi** [comment]
My french is very bad. I hope I understand you correctly. To receive attributes your CAS server needs to be configured to release attributes.

If you use saml you can use the saml example: https://github.com/Jasig/phpCAS/blob/master/docs/examples/example_advanced_saml11.php

Otherwise the CAS 3 protocol might help.

Anyway. For any support questions please head over to the mailing list. This tracker is for bugs/issues and not user support.

**Comment by marwaKotti** [comment]
my English is bad too ; so i want to display user's attributes such ( mail
, uid , name , givenName ... ) but i only have his login !!



Cordialement

Kotti Marwa
--------------------------------------------------------------


2016-02-22 19:56 GMT+01:00 Joachim Fritschi <notifications@github.com>:
