### ISSUE TITLE
CasAuthenticationException on google app engine

### ISSUE THREAD

**Issue by mgallegos** [Jasig/phpCAS#185]
When executing phpCAS::forceAuthentication() I get the following error on google app engine (I'm using the lastest version):

in Sso.php line 150
at Sso->authenticate()
at call_user_func_array(array(object(Sso), 'authenticate'), array()) in CasManager.php line 62
at CasManager->__call('authenticate', array()) in Facade.php line 213
at CasManager->authenticate() in Facade.php line 213

**Comment by jfritschi** [comment]
Sorry, but we cannot investigate integration of errors of phpcas with specific software.

Please troubleshoot the issue yourself:
https://wiki.jasig.org/display/CASC/phpCAS+troubleshooting

This will help you understand the issue. If your problem is phpcas code related please open an issue or  for generic issues/questions please consult the mailing list for community support. Please always include a debug log because we cannot guess/reproduce the specific setup/problems your specifc integration has.
