### ISSUE TITLE
CAS Server Logout

### ISSUE THREAD

**Issue by sensri** [Jasig/phpCAS#195]
Hi,

If we signout in "CAS" Server, our local application does not logout.

If we logout in CAS Server, then client website also have to logout. Is there any option for this. If there please explain me, it will very help to solve our problem.

Regards,
Senthilkumar

**Comment by jfritschi** [comment]
You have to enable the feature:

https://wiki.jasig.org/display/CASC/phpCAS+examples#phpCASexamples-HandlelogoutrequestsfromtheCASserver

Be sure that your application is https and check the debug logs of the phpcas client and cas server if it does not work.
Please also consider user behavior/understanding of a federated login before using this feature. Many people don't understand a "global" logout that kills open sessions and unsaved data in other websites that seem unrelated. Please consider a warning screen before a global logout.

**Comment by phpsen** [comment]
Thanks for your information. 

I think my question is wrong. Since i need to validate CAS server ticket for each request from client. Is there any option to validate to ticket for each request. 

Regards,
Senthilkumar

**Comment by jfritschi** [comment]
Check out the renew function of phpcas:

http://downloads.jasig.org/cas-clients/php/current/docs/api/index.html

This is however usually not the way cas should be used to authenticate every call. Renew is meant for a very sensitive subsite where you want to recheck with cas. Otherwise a phpcas site should maintain a local session spawned of the global cas session.

**Comment by phpsen** [comment]
Hi,

Do you have any example for single sign out without SAML. If you have any examples, please share that file. It will help me to integrate SSO easily.

Thanks in advance.

Regards,
Senthilkumar
