### ISSUE TITLE
getting the last response

### ISSUE THREAD

**Issue by greg0ire** [Jasig/phpCAS#199]
Is there any way to get the last response from the client ? I would like to add it to my logs if a given attribute cannot be found.

**Comment by jfritschi** [comment]
Not sure what you mean by response.

If you enable the debug log most info should be in there and you can extraxt where and how it is logged. You should be able to use one of our callback functions to run your code to extract the info at the right moment during authentication.

**Comment by greg0ire** [comment]
> Not sure what you mean by response.

I mean the content of [https://github.com/Jasig/phpCAS/blob/master/source/CAS/Client.php#L2801](this variable), which I indeed found in the log (among other things that I don't really care about). I can't see a call to any callback function in this method, so I guess it won't be possible to extract the information from there… any ideas?

**Comment by jfritschi** [comment]
Please check out the setPostAuthenticateCallback() method. You can hook your code into the function that is called after authentication.

Please check the API docs for some rudimentary docs on the function. Not sure if we have more on the wiki.

**Comment by greg0ire** [comment]
The post authenticate callback is called from `isAuthenticated`, not from `_readUrl`, so I cannot access the `$body` variable from it, can I ? BTW, this variable is not used at all… would you be interested in a PR maybe?

**Comment by jfritschi** [comment]
Be carefull about the $body. It's passed as a reference to the function and should be available to some degree inside the authentication code path.

**Comment by greg0ire** [comment]
Indeed, `$text_response` is the name of this variable inside the `isAuthenticated` method, but I can't see how to access this variable from the callback, who is only passed : 

- `$logoutTicket`
- `_postAuthenticateCallbackArgs` (which, if I understand correctly, is an array of arbitrary variables that I can provide myself).

**Comment by jfritschi** [comment]
During callback registration you can just set your function and wish list of variables to be passed.

During the authentication flow phpcas simply calls the function and passes the arguments you specified.

**Comment by greg0ire** [comment]
> During the authentication flow phpcas simply calls the function and passes the arguments you specified.

You talk about [this piece of code](https://github.com/Jasig/phpCAS/blob/master/source/CAS/Client.php#L1480)

I don't think you can just pass `call_user_func_array` variable names : [the documentation](http://fr.php.net/manual/en/function.call-user-func-array.php) says otherwise : 

>     The parameters to be passed to the callback, as an indexed array.

and so does [this simple test](https://3v4l.org/MTLgG)

If you want this to work like you describe, you will have to call `compact` to gather variables from the current context. Or am I missing something ?

**Comment by jfritschi** [comment]
Maybe I'm getting it wrong. I did not write or use this code. 

Maybe @adamfranco can help out?

**Comment by greg0ire** [comment]
BTW, I see that the CAS builds request objects, which implementation defaults to a custom wrapper of curl. Why not delegate this task to an external library? This has been done [over](https://github.com/kriswallsmith/Buzz) and [over](https://github.com/guzzle/guzzle) again, to the point that HTTP messages (requests and responses objects) have been [standardized](http://www.php-fig.org/psr/psr-7/), and [an http abstraction ](https://github.com/php-http/httplug) has been developed. Using that kind of abstraction would allow you to play a bit more nicely with the user.

**Comment by greg0ire** [comment]
ping @adamfranco

**Comment by greg0ire** [comment]
ping @adamfranco

**Comment by greg0ire** [comment]
@adamfranco , do you copy ?

**Comment by greg0ire** [comment]
Ok this is going nowhere.

**Comment by adamfranco** [comment]
Hi @greg0ire , my apologies for taking a while to weigh in. I wasn't closely following this thread and missed the mentions -- probably due to accidentally hitting "mute" instead of "archive" while plowing through my inbox. Once again, sorry for the delay.

> BTW, I see that the CAS builds request objects, which implementation defaults to a custom wrapper of curl. Why not delegate this task to an external library? This has been done over and over again, to the point that HTTP messages (requests and responses objects) have been standardized, and an http abstraction has been developed. Using that kind of abstraction would allow you to play a bit more nicely with the user.

I appreciate the sentiment above and would support an initiative to rework phpCAS to use a different HTTP wrapper library if it was useful to the community. For context though, phpCAS as a project is much older than any of the libraries you reference and was originally implemented on PHP 4, then upgraded over the years. These modern wrappers either didn't exist or weren't standardized during previous refactoring efforts in 2011. The PSR-7 draft was publish in late 2014 and was only adopted in 2015. Similarly, I've found that even relying on the "official" PECL-HTTP library can be problematic on some hosts, leaving cURL as the long-time historically broadly available option. Long story short, the use of cURL hasn't changed because no one has submitted patches to change it yet and there hasn't been a reason proposed for doing so.

A second, challenge is that phpCAS is specifically designed to hide as much of the communication protocol as possible from client applications. If phpCAS exposes state, data, or a method to the client, then it should be something that the client can rely on even if the target CAS server gets replaced (Apero CAS server, Ruby CAS, Drupal CAS, etc) or the protocol updated. The individual requests & responses are implementation details that might change every installation (such as based on availability of cURL or another transport), or by switching between CAS 1.0 protocol, CAS 2.0 protocol, or SAML 1.1 protocol. PhpCAS is open-source software, so any user is welcome to customize their own installation or fork of it to their particular needs -- that said the project as a whole has a responsibility to encourage interoperability and not expose too much of the internals. In the days prior to phpCAS 1.2, the internals of phpCAS were exposed to clients and many clients leveraged this access in "interesting" ways. Many of these clients were trying to solve real problems for themselves but ended up using the library in ways that caused their implementations to break with every change to the library. Since that time we've been attempting to provide abstracted interfaces for client applications to access so that the internal implementation can be modified and improved without breaking usage.

All that said, if the goal is to do improved, conditional logging, one broadly useful option would be to rework the logging system (currently implemented by `phpCAS::trace()`) to allow pluggable loggers of a defined interface to be configured into the library. Such loggers would then be passed request/response data from all internal methods (remember, there may be multiple requests and responses in an authentication sequence, or no request/response in the case of SAML 2.0 [which is not yet supported, but might be]).

Best,
Adam

**Comment by greg0ire** [comment]
Wow! Thanks for the thorough answer, this might be going somewhere actually!
You're right, this library is quite old, but I think it can still evolve, especially if you use deprecation mechanisms, like described [here](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/CONTRIBUTING.md#the-base-branch).

Indeed the logging system could use a rework, and would be a great place to start since you're hardly going to break anything by refactoring this.

>  allow pluggable loggers of a defined interface

I cannot recommend `Psr\Log\LoggerInterface` enough for this. It's **THE** interface you'll want to consume.
