### ISSUE TITLE
Logout replication issue

### ISSUE THREAD

**Issue by David-Wolowicz** [Jasig/phpCAS#213]
Hiya,

We are getting an error with the log-out replication code.

Fatal error:  Call to private method CAS_Request_CurlRequest::_initAndConfigure
() from context 'CAS_Request_CurlMultiRequest' in /usr/local/php5.6/lib/php/CAS/Request/CurlMultiRequest.php on line 115

It looks like the CurlMultiRequest.php calls a private method in CurlRequest when it tries to create an instance of the request for re-broadcast. I think the line numbers are off because we have an older version of phpCAS1.3, but, on line 125:

$request->_initAndConfigure();

and in line 102 of CurlRequest.php:

private function _initAndConfigure()

Thanks

Dave

**Comment by jfritschi** [comment]
I guess we screwed up the visibility during some refactoring. You probably can work around this problem by simply making the function public.

**Comment by gboddin** [comment]
protected wouldn't work in this case, since CurlRequest and CurlMultiRequest are not shared any abstract or class.

Ideally we should find a way for CurlMultiRequest to extend CurlRequest and then we could set it protected.

I'm a bit afraid to touch at this for the stable release since it would involve a bit of refactoring.

**Comment by jfritschi** [comment]
Should be fixed now
