### ISSUE TITLE
Renew Support Broken

### ISSUE THREAD

**Issue by serac** [Jasig/phpCAS#93]
Support for forced authentication via the CAS protocol renew parameter is apparently broken in recent versions. Formerly the following directive used to provide the correct functionality:

    phpCAS::forceAuthentication(true);

The forceAuthentication method no longer takes a boolean, and it appears that the `renewAuthentication` method is intended to provide similar functionality now, but it doesn't work as expected. When I replace the above with the following, I am repeatedly directed to the CAS login page with the renew parameter:

    phpCAS::renewAuthentication();

That's to say access to the phpCAS-enabled app is blocked by repeated redirects to CAS for forced auth. I also tried the following, which doesn't trigger forced authentication:

    phpCAS::forceAuthentication();

Perhaps this is merely a documentation issue and I'm ignorant, but it seems like renew is broken.

**Comment by serac** [comment]
I'm still seeing the same behavior with 1.3.3, which is what @thegolddustrush described above. What additional information do you need to troubleshoot further? This is an important CAS client for us and we need renew capability in our environment.

**Comment by serac** [comment]
I think it's fair to consider this a security issue, so I marked it accordingly.

**Comment by jfritschi** [comment]
I did a lot of digging through the code. I believe renew never worked with phpcas. I checked all branches back and can't find any code that uses "renew=true" to validate tickets. I think many years ago someone added the "redirect" part but never got around to the validation bits...

I can't reproduce any correct renew behaviour with older version so far.

@serac: I also checked the old versions for any support of `phpCAS::forceAuthentication(true);`. No luck in all versions since 1.0.  Any pointers to a working version would be appreciated.

It looks to me that the whole renew code needs to be written and not just "fixed".

**Comment by jfritschi** [comment]
I have implemented the renew function in master but have only done minimal testing. Please do some testing and give me some feedback.

**Comment by serac** [comment]
Just saw this. I'll do some testing and report back.

**Comment by jfritschi** [comment]
@serac Have you done some testing yet?

**Comment by jfritschi** [comment]
No negative feedback, so I assume it's fixed. Please reopen if there is still any issue.
